"""Partial-deflection post-pass: can on-axis partial deflections beat ESS-only on a
built plan, purely for ANIM SYNCING? (Frontier-free local refinement -- no search blowup.)

IDEA (user, 2026-06-30): the build planner steers/syncs with discrete ESS frames only.
The sim already supports an on-axis PARTIAL deflection via step('ess:<rawY>') -- stick
(128, rawY) routed through the same live-validated /54 magnitude law (sim.py:707). A
deflection deeper than ESS (raw 110, offset 18) bleeds MORE potential speed but keeps the
full-|v| displacement factor (1.0) and no 180 flip, and -- by lowering next-frame v -- it
SLOWS the anim advance (incr(v,air)), nudging head-bob phase. So a partial frame can re-aim
the bob peak onto a toward-target frame. It WINS only if that phase realignment buys back
more displacement than the extra decay costs. This script measures exactly that.

METHOD (zero frontier cost): take the validated ESS-only baseline plan, hill-climb single
ESS frames against a small partial-deflection palette, accept a swap ONLY if continuous
arrival to `dest` strictly improves. O(frames x palette) re-sims; no A* frontier touched.

NOTE: the palette stays inside the LIVE-VALIDATED decay band (offset ~18..63, i.e. raw
65..110). Shallower than ESS falls into the unvalidated zero-decay deadzone (offset <15) and
is excluded. acts_to_seq() does NOT yet emit 'ess:<rawY>' for live replay -- wire that only
if this post-pass shows a real gain.

The baseline is generated by the planner itself (plan_min_frames, cold start) so the A/B is
apples-to-apples under one seed model -- this isolates the partial-deflection effect from any
seed-fidelity question (live-exact ColdState math is irrelevant to a relative comparison).

Usage: python partial_postpass.py [dest=20000] [passes=4]
"""
import sys
import os, sys  # >>> repo bootstrap: locate tww_sim/ package + ../tools/ (dolphin_mem)
_rb = os.path.dirname(os.path.abspath(__file__))
while _rb != os.path.dirname(_rb) and not os.path.exists(os.path.join(_rb, 'pyproject.toml')):
    _rb = os.path.dirname(_rb)
if _rb not in sys.path: sys.path.insert(0, _rb)
_tb = os.path.join(os.path.dirname(_rb), 'tools')
if _tb not in sys.path: sys.path.append(_tb)

from tww_sim.swim import sim as S
from tww_sim.swim.plan import plan_min_frames

COLD_ANIM = 0.06392288208007812          # live fresh cold-start display anim (golden_harness)

# On-axis partial deflections DEEPER than ESS, inside the validated band (offset 23..63).
PALETTE = ['ess:105', 'ess:100', 'ess:95', 'ess:85', 'ess:75', 'ess:65']


def seed():
    """Match plan_min_frames(cold_start=True)'s _seed_for exactly (sim.py model)."""
    s = S.SwimState(v=0.0, anim=COLD_ANIM, air=900)
    s.state = 54
    s._entry_tax = False
    return s


def arrival(acts, dest):
    """Continuous frame at which forward progress (-x) crosses `dest`, or None if the
    fixed-length plan never reaches it (a too-deep swap that bleeds speed -> reject)."""
    s = seed()
    prev = -s.x
    for i, a in enumerate(acts):
        s.step(a)
        cur = -s.x
        if cur >= dest:
            return (i + (dest - prev) / (cur - prev)) if cur > prev else float(i + 1)
        prev = cur
    return None


def main():
    o = dict(t.split('=', 1) for t in sys.argv[1:] if '=' in t)
    dest = float(o.get('dest', '20000'))
    passes = int(o.get('passes', '4'))

    r = plan_min_frames(dest, v=0.0, anim=COLD_ANIM, air=900,
                        actions=('ess', 'chg', 'neu'), cold_start=True,
                        entry_tax=False, verbose=False)
    if r['frames'] is None:
        print(f"planner did not reach dest={dest:.0f}"); return
    acts = list(r['actions'])
    base = arrival(acts, dest)
    if base is None:
        print(f"baseline never reaches dest={dest:.0f} in {len(acts)} frames"); return
    nb, nn = acts.count('chg'), acts.count('neu')
    print(f"baseline (planner ESS-only): {len(acts)} frames, arrival {base:.4f} "
          f"(dest {dest:.0f})  [{nb} chg, {nn} neu, {len(acts)-nb-nn} ess]\n")

    cur = list(acts)
    changes = []
    for p in range(passes):
        improved = False
        best_arr = arrival(cur, dest)
        for i in range(len(cur)):
            if cur[i] != 'ess':                 # only refine plain ESS hold/sync frames
                continue
            local_best, local_act = best_arr, None
            for cand in PALETTE:
                trial = list(cur); trial[i] = cand
                a = arrival(trial, dest)
                if a is not None and a < local_best - 1e-9:
                    local_best, local_act = a, cand
            if local_act is not None:
                cur[i] = local_act
                changes.append((i, local_act, best_arr - local_best))
                best_arr = local_best
                improved = True
        print(f"pass {p + 1}: arrival {best_arr:.4f}  ({base - best_arr:+.4f} fr vs baseline)")
        if not improved:
            break

    final = arrival(cur, dest)
    print(f"\nFINAL: arrival {final:.4f}  ({base - final:+.4f} frames vs ESS-only baseline)")
    print(f"  {len(changes)} ESS frame(s) swapped to partial deflections")
    for i, act, gain in changes[:20]:
        print(f"    frame {i}: ess -> {act}  ({gain:+.4f} fr)")
    if base - final < 1e-4:
        print("\n=> No improvement: on-axis partial deflection does NOT beat ESS for "
              "anim syncing here. The phase realignment never buys back the extra decay.\n"
              "   (Expected if the win is LATERAL -- that needs off-axis / arrow swimming, "
              "the 2-D model.)")


if __name__ == '__main__':
    main()
