"""Gates for `harness/tetrapush/two_roll.py` -- the 2-roll search's SEARCH-SPACE gates (session 41).

Two properties, both 0-ULP / exact, no tolerances (`[[zero-ulp-tests-only]]`):

  1. **CONTAINMENT** (Dereck's steer): the human's own recorded inputs must be a SUBSET of what the
     parameterization can emit. Not hardcoded -- `reachable_stick_fan` enumerates the full byte grid,
     so membership holds by construction; these gates assert we never narrow it again. Session 40's
     fan failed exactly this (it inverted world bearings through `stick_for_bearing`, whose image is
     only the maximal-radius octagon-boundary bytes -- 544 of 2280 aims) and that WAS the blocker.
  2. **FIDELITY**: fed the generated stream, the sim reproduces the recorded rolls 0-ULP.

Plus the measured fact the cycle design rests on: the main stick is INERT inside a FRONT_ROLL.
"""
import pytest

from harness.tetrapush import seeds, two_roll as T
from tww_sim.core.mathlib import main_stick_decode


@pytest.fixture(scope='module')
def env():
    return seeds.load_env()


def test_reachable_fan_is_the_full_byte_grid_not_the_stick_for_bearing_image():
    """The fan's atom is the stick BYTE PAIR, so its aim alphabet is everything the pad can express.
    `stick_for_bearing` emits only maximal-radius bytes, a strict and much smaller subset -- pinning
    the gap here is what stops the s40 narrowing from creeping back."""
    from tww_sim.land.plan_land._primitives import stick_for_bearing
    full = T.reachable_stick_fan(msd_min=1.0)
    angles = {a for a, _b in full}
    assert len(angles) == len(full)                     # deduped by decoded angle, exactly

    cs = 39428                                          # the state-2 roll-entry csangle
    sfb = {main_stick_decode(*stick_for_bearing(a, cs, msd=1.0))[0]
           for a in range(0, 0x10000, 4)}
    assert sfb < angles                                 # a STRICT subset
    assert len(sfb) * 3 < len(angles)                   # and dramatically coarser (544 vs 2280)


def test_fan_members_decode_to_their_own_angle():
    """Every alphabet member's bytes really decode to the angle it is filed under (the fan is the
    reachable set, not a nominal grid)."""
    for ang, b in T.reachable_stick_fan(msd_min=1.0):
        got, msd = main_stick_decode(*b)
        assert got == ang and msd >= 1.0


def test_containment_human_inputs_are_in_the_search_space(env):
    """THE sanity check: every aim the human delivers is a fan member, and both of his roll segments
    are emittable by `roll_stream` at some knob setting."""
    r = T.contains_human(env)
    assert r['aims_missing'] == []
    assert len(r['rolls']) == 2
    for d in r['rolls']:
        assert d['ok'], "recorded roll at f%d is not emittable: %s" % (d['entry'], d['knobs'])
    assert r['ok']


def test_fitted_knobs_are_the_human_s_actual_pattern(env):
    """The fitted knobs are read off his stream, and they are the two-phase shape the generator
    models: a short aim hold, A held 2, a mid-roll L PULSE (never a hold), then the post stick."""
    rolls = T.contains_human(env)['rolls']
    for d in rolls:
        k = d['knobs']
        assert k['a_hold'] == 2
        lo, hi = k['l_window']
        assert 0 < lo < hi < d['exit'] - d['a_frame']   # a pulse strictly inside the roll
    assert rolls[0]['knobs']['l_window'] == (5, 8)
    assert rolls[1]['knobs']['l_window'] == (3, 8)
    # cycle 2 moves the stick again when the pulse ends; cycle 1 does not -- the `post` knob exists
    # because of exactly this, and dropping it is what made cycle 2 unemittable.
    assert rolls[1]['knobs']['post'] != rolls[1]['knobs']['post_l']
    assert rolls[0]['knobs']['post'] == rolls[0]['knobs']['post_l']


@pytest.mark.parametrize('which', [0, 1])
def test_generated_stream_reproduces_recorded_roll_bit_exact(env, which):
    """FIDELITY, 0-ULP: from the human's own entry, the stream `roll_stream` generates -- with aim
    bytes taken from the FAN, not from his controller -- reproduces his roll exactly, both actors'
    positions and Link's facing, every frame. Closes the session-40 blocker."""
    r = T.reproduces_recorded_roll(env, which=which)
    assert r['first_diverge'] is None and r['ok']
    assert r['facing'] == r['facing_rec']
    # the generated bytes are NOT his bytes -- same decoded angle, different pair (the point of
    # deduping the alphabet by angle rather than by bytes).
    assert r['aim_generated'] != r['aim_human']
    assert main_stick_decode(*r['aim_generated'])[0] == main_stick_decode(*r['aim_human'])[0]


def test_main_stick_is_inert_inside_a_roll(env):
    """The measured fact the s39 cycle design rests on (and that s40 wrongly overturned): during a
    FRONT_ROLL the main stick does nothing. Pegging it to any extreme reproduces the recorded roll
    0-ULP, so the roll is a genuine zero-branch segment for the main stick and branching inside it
    is pure waste."""
    r = T.roll_is_stick_inert(env)
    assert r['ok']
    for s, (first, facing) in r['variants'].items():
        assert first is None and facing == r['rec_facing'], s
